version = 1

[credentials]

[credentials.users]

[credentials.users.pparker]
name = "Peter Parker"
hash_pw = "$2b$12$vBSjagYd7GQIXT9gMYL7teORuHfhdBSJXZ.s3gPYWSNy/5suIXm/S"

[credentials.users.rmiller]
name = "Rebecca Miller"
hash_pw = "$2b$12$LjHNnhOLqC3foLlUj/72z.fvgJ5WGaW8JgCWZ1asBX2pK0jXahO3q"
